/**
 * @desc add all the action as ActionTypes
 */

export const ActionTypes = {
  SET_SHOW_TV_ALL: "SET_SHOW_TV_ALL",
  SET_SHOW_TV_ERROR: "SET_SHOW_TV_ERROR",
  SET_SEASON_SHOW_TV_ALL: "SET_SSEASON_SHOW_TV_ALL",
  SET_SEASON_SHOW_TV_ERROR: "SET_SEASON_SHOW_TV_ERROR",
  SET_DRAMA_SHOW_TV_ALL: "SET_DRAMA_SHOW_TV_ALL",
};
